name: CI

on:
    push:
        branches: ["master"]
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: oven-sh/setup-bun@v2
            - run: bun i
            - run: bun run generate
            - name: Verify parser.c is up to date
              run: git diff --exit-code src/parser.c src/tree_sitter/parser.h
            - run: bun run test
